name: Build and Test in Docker Containers
on:
  workflow_dispatch:
  push:
    branches: [ pre-production ]
  pull_request:
    branches: [ pre-production, production ]
jobs:
  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build frontend test image
        run: docker build --target frontend -t frontend-test .

  build-backend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build backend test image
        run: docker build --target backend-build -t backend-test .

  test-frontend:
    runs-on: ubuntu-latest
    needs: [build-frontend-image]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run frontend unit tests in container
        run: docker run --rm frontend-test npm test -- --watchAll=false

  test-backend:
    runs-on: ubuntu-latest
    needs: [build-backend-image]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run backend unit tests in container
        run: docker run --rm backend-test mvn test
