name: Compile and Verify Project on Production Push

on:

  pull_request:
    branches:
      - Production
      - main

jobs:
  compile-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Compile project
        run: mvn compile
      - name: Verify project
        run: mvn verify
