name: Lint Codebase
permissions:
  contents: write
  statuses: write # 
on:
    workflow_call:
jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Run Super-Linter (slim)
        uses: super-linter/super-linter@v8
        env:
            VALIDATE_ALL_CODEBASE: true
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # DISABLE_GITHUB_STATUS: true
            OUTPUT_DETAILS: detailed
            DISABLE_ERRORS: true
            SAVE_SUPER_LINTER_OUTPUT: true
      - name: Upload Super-Linter output file
        uses: actions/upload-artifact@v4
        with:
            name: super-linter-output
            path: ./super-linter-output/super-linter
            if-no-files-found: error
            retention-days: 7