name: Lint Codebase
on:
  workflow_call:
jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Super-Linter
        uses: super-linter/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_GITHUB_STATUS: true
          OUTPUT_DETAILS: detailed
      - name: Convert Super-Linter logs to Markdown
        run: |
          LOGFILE="/tmp/lint/super-linter.log"
          MDREPORT="super-linter-report.md"
          echo "# Super-Linter Report" > "$MDREPORT"
          for linter in CHECKOV CSS DOCKERFILE_HADOLINT GITHUB_ACTIONS GITLEAKS GOOGLE_JAVA_FORMAT HTML JAVA JAVASCRIPT_ES JAVASCRIPT_PRETTIER JAVASCRIPT_STANDARD JSCPD JSON MARKDOWN NATURAL_LANGUAGE XML YAML; do
            echo "<details><summary>$linter</summary>" >> "$MDREPORT"
            grep -A 20 "$linter" "$LOGFILE" | sed 's/^/    /' >> "$MDREPORT"
            echo "</details>" >> "$MDREPORT"
          done
      - name: Upload Super-Linter Markdown report
        uses: actions/upload-artifact@v4
        with:
          name: super-linter-markdown-report
          path: super-linter-report.md
