name: Lint Codebase
permissions:
  contents: write
on:
  workflow_call:
jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Super-Linter (slim)
        uses: github/super-linter/slim@v6
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_GITHUB_STATUS: true
          OUTPUT_DETAILS: detailed
          DISABLE_ERRORS: true
          LOG_FILE: /tmp/super-linter.log
      - name: Convert Super-Linter logs to Markdown
        run: |
          LOGFILE="/tmp/super-linter.log"
          MDREPORT="super-linter-report.md"
          echo "# Super-Linter Report" > "$MDREPORT"
          if [ -f "$LOGFILE" ]; then
            cat "$LOGFILE" >> "$MDREPORT"
          else
            echo "Super-Linter log file not found." >> "$MDREPORT"
          fi
      - name: Insert Super-Linter report into README.md
        run: |
          REPORT=$(cat super-linter-report.md)
          awk -v report="$REPORT" '
            BEGIN {in_section=0}
            /<!-- SUPER_LINTER_REPORT_START -->/ {print; print report; in_section=1; next}
            /<!-- SUPER_LINTER_REPORT_END -->/ {in_section=0}
            !in_section {print}
          ' README.md > README.tmp && mv README.tmp README.md
      - name: Upload Super-Linter Markdown report (raw)
        uses: actions/upload-artifact@v4
        with:
          name: super-linter-markdown-report.md
          path: super-linter-report.md
          if-no-files-found: error
          retention-days: 7
      - name: Commit Super-Linter Markdown report to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cp super-linter-report.md lint-report.md
          git add lint-report.md
          git add README.md
          git commit -m "Update Super-Linter report [skip ci]" || echo "No changes to commit"
          git push
            

